codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 90%
        threshold: 2%

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "scripts/**/*"
  - "hardhat.config.js"
  - "**/*.test.js"
  - "**/*.spec.js"
